CREATE DATABASE BD_CAFETERIA
USE bd_cafeteria
 
CREATE TABLE CLIENTE (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
DNI_CLIENTE CHAR (8) UNIQUE NOT NULL,
NOMBRES VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL,
EDAD INT NOT NULL,
GENERO CHAR(1)NOT NULL,
DIRECCION VARCHAR(100) NOT NULL,
CELULAR CHAR(9) NOT NULL,
CORREO VARCHAR (80) UNIQUE NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TRABAJADOR (
ID_TRABAJADOR INT AUTO_INCREMENT PRIMARY KEY,
DNI_TRABAJADOR CHAR (8) UNIQUE NOT NULL,
NOMBRES VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
EDAD INT NOT NULL,
GENERO CHAR(1)NOT NULL,
DIRECCION VARCHAR(100) NOT NULL,
CELULAR CHAR(9) NOT NULL,
CORREO VARCHAR (80) UNIQUE NOT NULL,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
PASSWORD_HASH VARCHAR(255)NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRODUCTO(
ID_PRODUCTO CHAR (8) PRIMARY KEY,
NOMBRE_PRODUCTO VARCHAR(60) NOT NULL,
STOCK INT NOT NULL,
ID_CATEGORIA CHAR(8) NOT NULL
);

CREATE TABLE CATEGORIA(
ID_CATEGORIA CHAR(8) PRIMARY KEY,
NOM_CATEGORIA VARCHAR (60) NOT NULL
);

CREATE TABLE RESERVA (
ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
ID_CLIENTE INT NOT NULL,
COD_PAGO VARCHAR(20) UNIQUE NOT NULL,
FECHA_RESERVA DATETIME DEFAULT CURRENT_TIMESTAMP,
ESTADO_PAGO VARCHAR(20) DEFAULT 'PENDIENTE'
);

-- relacion entre ellas

ALTER TABLE PRODUCTO
ADD CONSTRAINT FK_RELACION1
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA);


ALTER TABLE RESERVA
ADD CONSTRAINT FK_RELACION2
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);

CREATE TABLE USUARIO ( 
ID INT AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR (60) UNIQUE NOT NULL,
PASSWORD_HASH VARCHAR (200) NOT NULL,
ESTADO TINYINT(1) DEFAULT 1
);

INSERT INTO USUARIO ( USERNAME, PASSWORD_HASH)
VALUES ('admin','$2y$10$heuMG7aElXF5IiS4rCN49.T.smRQfhlCmVuoAh/SPpjQ6YA6qzZO6
');

